import React from 'react';
import { render, screen } from '@testing-library/react';
import { vi } from 'vitest';
import { CheckinDetailsScreen } from '../../components/CheckinDetailsScreen';
import { ThemeCardManager } from '../../utils/ThemeCardManager';

// Mock localStorage
const localStorageMock = (() => {
  let store: Record<string, string> = {};

  return {
    getItem: (key: string) => store[key] || null,
    setItem: (key: string, value: string) => {
      store[key] = value.toString();
    },
    removeItem: (key: string) => {
      delete store[key];
    },
    clear: () => {
      store = {};
    }
  };
})();

Object.defineProperty(window, 'localStorage', {
  value: localStorageMock
});

// Mock content context
vi.mock('../../components/ContentContext', () => ({
  useContent: () => ({
    content: {
      ui: {
        cards: {
          final: {
            why: 'Why?'
          },
          startExercise: 'Ready to start the exercise?'
        },
        navigation: {
          continue: 'Continue'
        }
      }
    },
    getLocalizedText: (text: string) => text,
    getCard: (cardId: string) => ({
      id: cardId,
      title: 'Test Card',
      questions: [
        { text: 'Question 1' },
        { text: 'Question 2' }
      ],
      finalMessage: {
        message: 'Test message',
        practiceTask: 'Test task',
        whyExplanation: 'Test explanation'
      }
    })
  })
}));

// Mock components
vi.mock('../../components/BottomFixedButton', () => ({
  BottomFixedButton: ({ children, onClick }: { children: React.ReactNode; onClick: () => void }) => (
    <button onClick={onClick} data-testid="continue-button">
      {children}
    </button>
  )
}));

vi.mock('../../components/ProfileLayoutComponents', () => ({
  MiniStripeLogo: () => <div data-testid="mini-logo">Logo</div>
}));

// Mock ThemeLoader to return predictable theme/card data for async flow
vi.mock('../../utils/ThemeLoader', () => ({
  ThemeLoader: {
    loadTheme: vi.fn(async (_themeId: string, _language: string) => ({
      id: 'stress-management',
      title: 'Stress',
      description: 'desc',
      welcomeMessage: 'welcome',
      isPremium: false,
      cards: [
        {
          id: 'card-1',
          level: 1,
          introduction: 'intro',
          questions: ['Question 1', 'Question 2'],
          technique: 'Test message',
          recommendation: 'Test task',
          mechanism: 'Test explanation'
        }
      ]
    }))
  }
}));

describe('CheckinDetailsScreen', () => {
  beforeEach(() => {
    localStorageMock.clear();
  });

  const mockProps = {
    onBack: vi.fn(),
    checkinId: 'card-1_2024-01-15_1',
    cardTitle: 'Test Card',
    checkinDate: '2024-01-15'
  };

  it('should display start exercise invitation when no completed attempts exist', async () => {
    // No completed attempts added
    render(<CheckinDetailsScreen {...mockProps} />);

    // Wait for async load to settle and invitation to appear
    expect(await screen.findByText('Ready to start the exercise?')).toBeInTheDocument();
  });

  it('should display completed attempt data when attempt exists', async () => {
    // Add a completed attempt
    const answers = { 'question1': 'My answer to question 1', 'question2': 'My answer to question 2' };
    const updatedProgress = ThemeCardManager.addCompletedAttempt('card-1', answers, 4);
    const attemptId = updatedProgress.completedAttempts[0].attemptId;

    // Use the actual attemptId generated by ThemeCardManager
    const propsWithRealAttemptId = {
      ...mockProps,
      checkinId: attemptId
    };

    render(<CheckinDetailsScreen {...propsWithRealAttemptId} />);

    // Should show the completed attempt data (await async rendering)
    expect(await screen.findByText('My answer to question 1')).toBeInTheDocument();
    expect(await screen.findByText('My answer to question 2')).toBeInTheDocument();
    expect(await screen.findByText('Test message')).toBeInTheDocument();
    expect(await screen.findByText('Test task')).toBeInTheDocument();
  });

  it('should call onBack when continue button is clicked', () => {
    render(<CheckinDetailsScreen {...mockProps} />);

    const continueButton = screen.getByTestId('continue-button');
    continueButton.click();

    expect(mockProps.onBack).toHaveBeenCalledTimes(1);
  });

  it('should display card title in header', async () => {
    render(<CheckinDetailsScreen {...mockProps} />);

    // Should show card title in header (text is split across elements)
    expect(await screen.findByText(/Test Card/)).toBeInTheDocument();
  });
});
